Hw05 parallel execution
ex3294-23/hw-okochanov pull request #6
Opened 2023-01-24 17:42 UTC by ex3294-23

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-24 20:38 UTC, vladislavmass requested changes
Работа хорошая. Код написан крайне лаконично. Принять не могу, так как нет новых unit тестов.

2023-01-24 20:38 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	var z int32
Имя переменной не говорит о том, для чего она нужна.

2023-01-25 13:35 UTC, ex3294-23 commented on hw05_parallel_execution/run.go
> +	var z int32
https://cdn.otus.ru/media/public/f6/6f/localhost_8080_13_sync_primitives_p2__15-20807-f66fa7.pdf
34 слайд, сделанно по аналогии. 
wg - группа ожидания. В коде объявлена в явном виде на 16 страке. 
Думаю, что предоставленую информацию с курсов можно считать за best practice!?

2023-01-25 14:30 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	var z int32
К wg нет никаких вопросов. Это общепринятое имя для wait group. Вопрос к 18 строке.

2023-01-25 14:46 UTC, ex3294-23 commented on hw05_parallel_execution/run.go
> +	var z int32
z на v поменять, более лаконично будет ?

2023-01-25 14:53 UTC, vladislavmass approved these changes
Решение хорошее, имя модуля верное. Тестов добавлено мало, есть несколько стилистических замечаний. Работа принята. Оценка 7/10.

Оценку можно исправить добавлением тестов и исправлением стилистических замечаний.

2023-01-25 14:53 UTC, vladislavmass commented on hw05_parallel_execution/run_test.go
> +		result := Run(tasks, workersCount, maxErrorsCount)
Имя rezult тут является ошибочным. Правильнее было бы назвать это err

2023-01-25 14:57 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +	var z int32
Лучше это назвать errCounter.

2023-01-25 15:04 UTC, ex3294-23 commented on hw05_parallel_execution/run.go
> +	var z int32
Поправил.

2023-01-25 15:04 UTC, ex3294-23 commented on hw05_parallel_execution/run_test.go
> +		result := Run(tasks, workersCount, maxErrorsCount)
Поправил.

2023-01-25 15:15 UTC, hungry-honeybadger approved these changes
Стилистически правки приняты. Оценка увеличена о 8/10, Для большей оценки нужно добавить несколько unit тестов

2023-01-25 16:18 UTC, merged